# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speech.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='speech.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0cspeech.proto\"\x15\n\x05\x61udio\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x16\n\x05rtext\x12\r\n\x05value\x18\x01 \x01(\t21\n\x10SpeechTranslator\x12\x1d\n\ttranslate\x12\x06.audio\x1a\x06.rtext\"\x00\x62\x06proto3'
)




_AUDIO = _descriptor.Descriptor(
  name='audio',
  full_name='audio',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='audio.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=37,
)


_RTEXT = _descriptor.Descriptor(
  name='rtext',
  full_name='rtext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='rtext.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['audio'] = _AUDIO
DESCRIPTOR.message_types_by_name['rtext'] = _RTEXT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

audio = _reflection.GeneratedProtocolMessageType('audio', (_message.Message,), {
  'DESCRIPTOR' : _AUDIO,
  '__module__' : 'speech_pb2'
  # @@protoc_insertion_point(class_scope:audio)
  })
_sym_db.RegisterMessage(audio)

rtext = _reflection.GeneratedProtocolMessageType('rtext', (_message.Message,), {
  'DESCRIPTOR' : _RTEXT,
  '__module__' : 'speech_pb2'
  # @@protoc_insertion_point(class_scope:rtext)
  })
_sym_db.RegisterMessage(rtext)



_SPEECHTRANSLATOR = _descriptor.ServiceDescriptor(
  name='SpeechTranslator',
  full_name='SpeechTranslator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=63,
  serialized_end=112,
  methods=[
  _descriptor.MethodDescriptor(
    name='translate',
    full_name='SpeechTranslator.translate',
    index=0,
    containing_service=None,
    input_type=_AUDIO,
    output_type=_RTEXT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPEECHTRANSLATOR)

DESCRIPTOR.services_by_name['SpeechTranslator'] = _SPEECHTRANSLATOR

# @@protoc_insertion_point(module_scope)
