version: '3'
services:

  server1:
    build:
      context: ./sample/server1
      dockerfile: Dockerfile
    expose:
      - "50051"
      
  server2:
    build:
      context: ./sample/server2
      dockerfile: Dockerfile
    expose:
      - "50052"
    
  server3:
    build:
      context: ./sample/server3
      dockerfile: Dockerfile
    expose:
      - "50053"
      
  server4:
    build:
      context: ./sample/server4
      dockerfile: Dockerfile
    expose:
      - "50054"
      
  haproxy:
    image: haproxytech/haproxy-ubuntu:1.9.2
    volumes:
      - "./sample/haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg"
      - "./sample/creds/haproxy.pem:/etc/haproxy/pem/haproxy.pem"
      - "./sample/creds/server.crt:/etc/haproxy/pem/server.crt"
    depends_on:
      - server1
      - server2
      - server3
      - server4
      
  client:
#    image: haproxytechblog/grpc-sample-client
    build:
      context: ./sample/client
      dockerfile: Dockerfile
    environment:
    - "SERVER_ADDRESS=haproxy:3001"
    - "Enter_Number1_here=114"
    - "Enter_Number2_here=8"
    - "Text=morning"
    - "dest=ja"
    - "log_file=sample.log"
#    - "TLS_CERT=haproxy.crt"
    depends_on:
    - haproxy
      
