version: '3'
services:

  server1:
    build:
      context: ./sample/server1
      dockerfile: Dockerfile
    environment:
      - "port=50051"
    expose:
      - "50051"
      
  server1_1:
    build:
      context: ./sample/server1
      dockerfile: Dockerfile
    environment:
      - "port=50055"
    expose:
      - "50055"
      
  server1_2:
    build:
      context: ./sample/server1
      dockerfile: Dockerfile
    environment:
      - "port=50056"
    expose:
      - "50056"
      
  server2:
    build:
      context: ./sample/server2
      dockerfile: Dockerfile
    environment:
      - "port=50052"
    expose:
      - "50052"
    
  server3:
    build:
      context: ./sample/server3
      dockerfile: Dockerfile
    volumes:
      - "./sample/server3/<key-file>:/etc/<key-file>"
    environment:
      - "GOOGLE_APPLICATION_CREDENTIALS=/etc/<key-file>"
      - "port=50053"
    expose:
      - "50053"
      
  server3_1:
    build:
      context: ./sample/server3
      dockerfile: Dockerfile
    volumes:
      - "./sample/server3/<key-file>:/etc/<key-file>"
    environment:
      - "GOOGLE_APPLICATION_CREDENTIALS=/etc/<key-file>"
      - "port=50060"
    expose:
      - "50060"
      
  server3_2:
    build:
      context: ./sample/server3
      dockerfile: Dockerfile
    volumes:
      - "./sample/server3/<key-file>:/etc/<key-file>"
    environment:
      - "GOOGLE_APPLICATION_CREDENTIALS=/etc/<key-file>"
      - "port=50061"
    expose:
      - "50061"
      
  server4:
    build:
      context: ./sample/server4
      dockerfile: Dockerfile
    environment:
      - "port=50054"
    expose:
      - "50054"
      
  haproxy:
    image: haproxytech/haproxy-ubuntu:1.9.2
    volumes:
      - "./sample/haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg"
      - "./sample/creds/haproxy.pem:/etc/haproxy/pem/haproxy.pem"
      - "./sample/creds/server.crt:/etc/haproxy/pem/server.crt"
    depends_on:
      - server1
      - server2
      - server3
      - server4
      - server1_1
      - server1_2
      - server3_1
      - server3_2
      
  client:
#    image: haproxytechblog/grpc-sample-client
    build:
      context: ./sample/client
      dockerfile: Dockerfile
    volumes:
      - "./sample/client/:/etc/data1/"
    environment:
    - "SERVER_ADDRESS=haproxy:3001"
    - "Enter_Number1_here=114"
    - "Enter_Number2_here=8"
    - "Text=good morning"
    - "dest=ru"
    - "log_file=sample.log"
#    - "TLS_CERT=haproxy.crt"
    depends_on:
    - haproxy
    
  client1:
    build:
      context: ./sample/client1
      dockerfile: Dockerfile
    volumes:
    - "./sample/client1/:/etc/data/"
    environment:
    - "SERVER_ADDRESS=haproxy:3001"
    depends_on:
    - haproxy
  
  client2:
    build:
      context: ./sample/client2
      dockerfile: Dockerfile
    environment:
    - "SERVER_ADDRESS=haproxy:3001"
    - "Text=good morning"
    - "dest=ru"
    depends_on:
    - haproxy
    
  client3:
    build:
      context: ./sample/client3
      dockerfile: Dockerfile
    volumes:
    - "./sample/client3/:/etc/data3/"
    environment:
    - "SERVER_ADDRESS=haproxy:3001"
    - "dest=hi"
    depends_on:
    - haproxy
    
  client4:
    build:
      context: ./sample/client4
      dockerfile: Dockerfile
    volumes:
    - "./sample/client4/:/etc/data4/"
    environment:
    - "SERVER_ADDRESS=haproxy:3001"
    - "dest=hi"
    depends_on:
    - haproxy
      
      
