# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: total.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='total.proto',
  package='total',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0btotal.proto\x12\x05total\":\n\x0bservice_add\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"\x1c\n\x0cservice_name\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"$\n\nAddRequest\x12\n\n\x02n1\x18\x01 \x01(\x05\x12\n\n\x02n2\x18\x02 \x01(\x05\"\x16\n\x08\x41\x64\x64Reply\x12\n\n\x02n1\x18\x01 \x01(\x05\"*\n\x10SubstractRequest\x12\n\n\x02n1\x18\x01 \x01(\x05\x12\n\n\x02n2\x18\x02 \x01(\x05\"\x1c\n\x0eSubstractReply\x12\n\n\x02n1\x18\x01 \x01(\x05\")\n\x0fMultiplyRequest\x12\n\n\x02n1\x18\x01 \x01(\x05\x12\n\n\x02n2\x18\x02 \x01(\x05\"\x1b\n\rMultiplyReply\x12\n\n\x02n1\x18\x01 \x01(\x05\"\'\n\rDivideRequest\x12\n\n\x02n1\x18\x01 \x01(\x05\x12\n\n\x02n2\x18\x02 \x01(\x05\"\x19\n\x0b\x44ivideReply\x12\n\n\x02\x66\x31\x18\x01 \x01(\x02\"#\n\x04Text\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x65st\x18\x02 \x01(\t\"\x1b\n\nreturntext\x12\r\n\x05value\x18\x01 \x01(\t2G\n\x0cserviceguide\x12\x37\n\nGetservice\x12\x13.total.service_name\x1a\x12.total.service_add\"\x00\x32z\n\x07Greeter\x12\x34\n\x08SayHello\x12\x13.total.HelloRequest\x1a\x11.total.HelloReply\"\x00\x12\x39\n\rSayHelloAgain\x12\x13.total.HelloRequest\x1a\x11.total.HelloReply\"\x00\x32\xea\x01\n\nCalculator\x12+\n\x03\x41\x64\x64\x12\x11.total.AddRequest\x1a\x0f.total.AddReply\"\x00\x12=\n\tSubstract\x12\x17.total.SubstractRequest\x1a\x15.total.SubstractReply\"\x00\x12:\n\x08Multiply\x12\x16.total.MultiplyRequest\x1a\x14.total.MultiplyReply\"\x00\x12\x34\n\x06\x44ivide\x12\x14.total.DivideRequest\x1a\x12.total.DivideReply\"\x00\x32;\n\nTranslator\x12-\n\tGoogTrans\x12\x0b.total.Text\x1a\x11.total.returntext\"\x00\x62\x06proto3'
)




_SERVICE_ADD = _descriptor.Descriptor(
  name='service_add',
  full_name='total.service_add',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='total.service_add.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='total.service_add.port', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='total.service_add.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=80,
)


_SERVICE_NAME = _descriptor.Descriptor(
  name='service_name',
  full_name='total.service_name',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='total.service_name.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=110,
)


_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='total.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='total.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=140,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='total.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='total.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=171,
)


_ADDREQUEST = _descriptor.Descriptor(
  name='AddRequest',
  full_name='total.AddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n1', full_name='total.AddRequest.n1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n2', full_name='total.AddRequest.n2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=209,
)


_ADDREPLY = _descriptor.Descriptor(
  name='AddReply',
  full_name='total.AddReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n1', full_name='total.AddReply.n1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=233,
)


_SUBSTRACTREQUEST = _descriptor.Descriptor(
  name='SubstractRequest',
  full_name='total.SubstractRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n1', full_name='total.SubstractRequest.n1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n2', full_name='total.SubstractRequest.n2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=277,
)


_SUBSTRACTREPLY = _descriptor.Descriptor(
  name='SubstractReply',
  full_name='total.SubstractReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n1', full_name='total.SubstractReply.n1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=307,
)


_MULTIPLYREQUEST = _descriptor.Descriptor(
  name='MultiplyRequest',
  full_name='total.MultiplyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n1', full_name='total.MultiplyRequest.n1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n2', full_name='total.MultiplyRequest.n2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=350,
)


_MULTIPLYREPLY = _descriptor.Descriptor(
  name='MultiplyReply',
  full_name='total.MultiplyReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n1', full_name='total.MultiplyReply.n1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=379,
)


_DIVIDEREQUEST = _descriptor.Descriptor(
  name='DivideRequest',
  full_name='total.DivideRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n1', full_name='total.DivideRequest.n1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n2', full_name='total.DivideRequest.n2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=420,
)


_DIVIDEREPLY = _descriptor.Descriptor(
  name='DivideReply',
  full_name='total.DivideReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='f1', full_name='total.DivideReply.f1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=422,
  serialized_end=447,
)


_TEXT = _descriptor.Descriptor(
  name='Text',
  full_name='total.Text',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='total.Text.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dest', full_name='total.Text.dest', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=449,
  serialized_end=484,
)


_RETURNTEXT = _descriptor.Descriptor(
  name='returntext',
  full_name='total.returntext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='total.returntext.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=486,
  serialized_end=513,
)

DESCRIPTOR.message_types_by_name['service_add'] = _SERVICE_ADD
DESCRIPTOR.message_types_by_name['service_name'] = _SERVICE_NAME
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['AddRequest'] = _ADDREQUEST
DESCRIPTOR.message_types_by_name['AddReply'] = _ADDREPLY
DESCRIPTOR.message_types_by_name['SubstractRequest'] = _SUBSTRACTREQUEST
DESCRIPTOR.message_types_by_name['SubstractReply'] = _SUBSTRACTREPLY
DESCRIPTOR.message_types_by_name['MultiplyRequest'] = _MULTIPLYREQUEST
DESCRIPTOR.message_types_by_name['MultiplyReply'] = _MULTIPLYREPLY
DESCRIPTOR.message_types_by_name['DivideRequest'] = _DIVIDEREQUEST
DESCRIPTOR.message_types_by_name['DivideReply'] = _DIVIDEREPLY
DESCRIPTOR.message_types_by_name['Text'] = _TEXT
DESCRIPTOR.message_types_by_name['returntext'] = _RETURNTEXT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

service_add = _reflection.GeneratedProtocolMessageType('service_add', (_message.Message,), {
  'DESCRIPTOR' : _SERVICE_ADD,
  '__module__' : 'total_pb2'
  # @@protoc_insertion_point(class_scope:total.service_add)
  })
_sym_db.RegisterMessage(service_add)

service_name = _reflection.GeneratedProtocolMessageType('service_name', (_message.Message,), {
  'DESCRIPTOR' : _SERVICE_NAME,
  '__module__' : 'total_pb2'
  # @@protoc_insertion_point(class_scope:total.service_name)
  })
_sym_db.RegisterMessage(service_name)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'total_pb2'
  # @@protoc_insertion_point(class_scope:total.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'total_pb2'
  # @@protoc_insertion_point(class_scope:total.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

AddRequest = _reflection.GeneratedProtocolMessageType('AddRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDREQUEST,
  '__module__' : 'total_pb2'
  # @@protoc_insertion_point(class_scope:total.AddRequest)
  })
_sym_db.RegisterMessage(AddRequest)

AddReply = _reflection.GeneratedProtocolMessageType('AddReply', (_message.Message,), {
  'DESCRIPTOR' : _ADDREPLY,
  '__module__' : 'total_pb2'
  # @@protoc_insertion_point(class_scope:total.AddReply)
  })
_sym_db.RegisterMessage(AddReply)

SubstractRequest = _reflection.GeneratedProtocolMessageType('SubstractRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSTRACTREQUEST,
  '__module__' : 'total_pb2'
  # @@protoc_insertion_point(class_scope:total.SubstractRequest)
  })
_sym_db.RegisterMessage(SubstractRequest)

SubstractReply = _reflection.GeneratedProtocolMessageType('SubstractReply', (_message.Message,), {
  'DESCRIPTOR' : _SUBSTRACTREPLY,
  '__module__' : 'total_pb2'
  # @@protoc_insertion_point(class_scope:total.SubstractReply)
  })
_sym_db.RegisterMessage(SubstractReply)

MultiplyRequest = _reflection.GeneratedProtocolMessageType('MultiplyRequest', (_message.Message,), {
  'DESCRIPTOR' : _MULTIPLYREQUEST,
  '__module__' : 'total_pb2'
  # @@protoc_insertion_point(class_scope:total.MultiplyRequest)
  })
_sym_db.RegisterMessage(MultiplyRequest)

MultiplyReply = _reflection.GeneratedProtocolMessageType('MultiplyReply', (_message.Message,), {
  'DESCRIPTOR' : _MULTIPLYREPLY,
  '__module__' : 'total_pb2'
  # @@protoc_insertion_point(class_scope:total.MultiplyReply)
  })
_sym_db.RegisterMessage(MultiplyReply)

DivideRequest = _reflection.GeneratedProtocolMessageType('DivideRequest', (_message.Message,), {
  'DESCRIPTOR' : _DIVIDEREQUEST,
  '__module__' : 'total_pb2'
  # @@protoc_insertion_point(class_scope:total.DivideRequest)
  })
_sym_db.RegisterMessage(DivideRequest)

DivideReply = _reflection.GeneratedProtocolMessageType('DivideReply', (_message.Message,), {
  'DESCRIPTOR' : _DIVIDEREPLY,
  '__module__' : 'total_pb2'
  # @@protoc_insertion_point(class_scope:total.DivideReply)
  })
_sym_db.RegisterMessage(DivideReply)

Text = _reflection.GeneratedProtocolMessageType('Text', (_message.Message,), {
  'DESCRIPTOR' : _TEXT,
  '__module__' : 'total_pb2'
  # @@protoc_insertion_point(class_scope:total.Text)
  })
_sym_db.RegisterMessage(Text)

returntext = _reflection.GeneratedProtocolMessageType('returntext', (_message.Message,), {
  'DESCRIPTOR' : _RETURNTEXT,
  '__module__' : 'total_pb2'
  # @@protoc_insertion_point(class_scope:total.returntext)
  })
_sym_db.RegisterMessage(returntext)



_SERVICEGUIDE = _descriptor.ServiceDescriptor(
  name='serviceguide',
  full_name='total.serviceguide',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=515,
  serialized_end=586,
  methods=[
  _descriptor.MethodDescriptor(
    name='Getservice',
    full_name='total.serviceguide.Getservice',
    index=0,
    containing_service=None,
    input_type=_SERVICE_NAME,
    output_type=_SERVICE_ADD,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICEGUIDE)

DESCRIPTOR.services_by_name['serviceguide'] = _SERVICEGUIDE


_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='total.Greeter',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=588,
  serialized_end=710,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='total.Greeter.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SayHelloAgain',
    full_name='total.Greeter.SayHelloAgain',
    index=1,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER


_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='total.Calculator',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=713,
  serialized_end=947,
  methods=[
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='total.Calculator.Add',
    index=0,
    containing_service=None,
    input_type=_ADDREQUEST,
    output_type=_ADDREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Substract',
    full_name='total.Calculator.Substract',
    index=1,
    containing_service=None,
    input_type=_SUBSTRACTREQUEST,
    output_type=_SUBSTRACTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Multiply',
    full_name='total.Calculator.Multiply',
    index=2,
    containing_service=None,
    input_type=_MULTIPLYREQUEST,
    output_type=_MULTIPLYREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Divide',
    full_name='total.Calculator.Divide',
    index=3,
    containing_service=None,
    input_type=_DIVIDEREQUEST,
    output_type=_DIVIDEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR


_TRANSLATOR = _descriptor.ServiceDescriptor(
  name='Translator',
  full_name='total.Translator',
  file=DESCRIPTOR,
  index=3,
  serialized_options=None,
  serialized_start=949,
  serialized_end=1008,
  methods=[
  _descriptor.MethodDescriptor(
    name='GoogTrans',
    full_name='total.Translator.GoogTrans',
    index=0,
    containing_service=None,
    input_type=_TEXT,
    output_type=_RETURNTEXT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSLATOR)

DESCRIPTOR.services_by_name['Translator'] = _TRANSLATOR

# @@protoc_insertion_point(module_scope)
