# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='log.proto',
  package='log',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\tlog.proto\x12\x03log\"\x18\n\x08\x66ilename\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x17\n\x07\x63ontent\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2:\n\x0blog_sharing\x12+\n\x08Get_file\x12\r.log.filename\x1a\x0c.log.content\"\x00\x30\x01\x62\x06proto3'
)




_FILENAME = _descriptor.Descriptor(
  name='filename',
  full_name='log.filename',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='log.filename.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=42,
)


_CONTENT = _descriptor.Descriptor(
  name='content',
  full_name='log.content',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='log.content.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['filename'] = _FILENAME
DESCRIPTOR.message_types_by_name['content'] = _CONTENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

filename = _reflection.GeneratedProtocolMessageType('filename', (_message.Message,), {
  'DESCRIPTOR' : _FILENAME,
  '__module__' : 'log_pb2'
  # @@protoc_insertion_point(class_scope:log.filename)
  })
_sym_db.RegisterMessage(filename)

content = _reflection.GeneratedProtocolMessageType('content', (_message.Message,), {
  'DESCRIPTOR' : _CONTENT,
  '__module__' : 'log_pb2'
  # @@protoc_insertion_point(class_scope:log.content)
  })
_sym_db.RegisterMessage(content)



_LOG_SHARING = _descriptor.ServiceDescriptor(
  name='log_sharing',
  full_name='log.log_sharing',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=69,
  serialized_end=127,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get_file',
    full_name='log.log_sharing.Get_file',
    index=0,
    containing_service=None,
    input_type=_FILENAME,
    output_type=_CONTENT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOG_SHARING)

DESCRIPTOR.services_by_name['log_sharing'] = _LOG_SHARING

# @@protoc_insertion_point(module_scope)
